### ISSUE TITLE
Issue - Shift+UP Not Fully Functional

### ISSUE THREAD

**Issue by FroggMaster** [YOURsammich/awakens#30]
Issue:
Shift+Up will only scroll through one message, rather than every previous message sent.

Intended Action:
Shift+Up should scroll through every message the user has sent.

**Comment by YOURsammich** [comment]
Need to figure out what causes this. Works for most users.

**Comment by FroggMaster** [comment]
Will investigate further during Developer meeting on Sunday.

Need to clear cache and do basic TS on my end as well.

**Comment by FroggMaster** [comment]
Has since been resolved.
