### ISSUE TITLE
Goal - Active Channel List

### ISSUE THREAD

**Issue by FroggMaster** [YOURsammich/awakens#32]
Goal:
List of all active channels with 1+ user's

Reason:
This would promote user activity and allow others to explore new communities/meet new people

Suggestion:
Command that brings up a GUI with list of active channels
Button next to each channel to switch channels/join active channel

**Comment by correcthorsebatterystaple-sudo** [comment]
My implementation of this is the front page to listing channels using a selection algorithm; similar to 8ch's boards system.
