### ISSUE TITLE
Issue - Fonts are Case Sensitive

### ISSUE THREAD

**Issue by FroggMaster** [YOURsammich/awakens#38]
Fonts are currently case sensitive

Ex. /font gloria hallelujah
Will not work but

/font Gloria Hallelujah
Will work

**Comment by michael-elbert** [comment]
Google API requires you to use the specific case for the font to load.

**Comment by FroggMaster** [comment]
Solutions to that:
1) Refuse input for font's that don't exist.
2) Search for matching fonts by name, change characters that aren't capitalize to match the closest font.
