### ISSUE TITLE
Issue - /AFK Message

### ISSUE THREAD

**Issue by FroggMaster** [YOURsammich/awakens#39]
Should not be able to set your /AFK message to "Unread PM(s)"
Or anything of that closely matches.

**Comment by DayDun** [comment]
Or we could just make the "Unread PM(s)" message look different than afk messages

**Comment by michael-elbert** [comment]
Kit and I have already worked out something that can be done for this. instead of "Unread PM(s)" it will show an orange indicator on the opposite side of the name from the typing indicator. We were working on this but the PM system is a bit wacky so we will have to look more into it.
