### ISSUE TITLE
Quoting a base64 image doesn't work.

### ISSUE THREAD

**Issue by michael-elbert** [YOURsammich/awakens#42]
![image](https://cloud.githubusercontent.com/assets/14222335/23651450/6c8273e6-02da-11e7-9d0f-7b285ff62c00.png)

**Comment by FroggMaster** [comment]
Not really sure what we're seeing in the picture.

**Comment by michael-elbert** [comment]
![image](https://cloud.githubusercontent.com/assets/14222335/23651450/6c8273e6-02da-11e7-9d0f-7b285ff62c00.png)

**Comment by michael-elbert** [comment]
Edited to show a better explanation.

**Comment by akhcade** [comment]
i helped for once, cool
