### ISSUE TITLE
Goal - Universal /get Command

### ISSUE THREAD

**Issue by FroggMaster** [YOURsammich/awakens#6]
Goal:
Universal /get command
/get *

Reason:
There will likely be a lot of variables that we want to get information for.
Being able to "/get topicinfo" or "/get channelowner", etc will be a handy feature.

Suggestion:
One command to pull all information that accepts multiple variables
/get \* (the \* being able be replaced by any variable that holds data.)

**Comment by YOURsammich** [comment]
The get command already works like this, it will get any data that is saved
